[package]
name = "cedar"
version = "0.0.1"
authors = ["Tom Schroeder <j.tom.schroeder@gmail.com>"]
description = "Reactive, functional library for creating GUI applications"

documentation = "https://docs.rs/cedar"
homepage = "https://github.com/jtomschroeder/cedar"
repository = "https://github.com/jtomschroeder/cedar"

readme = "README.md"
license = "MIT"
keywords = ["gui"]

[dependencies]
cocoa = "0.7"
objc = "0.2"
crossbeam = "0.2.10"
